pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK21'
    }

    stages {

        stage('Checkout Code') {
            steps {
                cleanWs()
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/varsharitu55/kalp-ashram-digital-platform.git'
            }
        }

        stage('Build, Test & SonarQube Analysis') {
            steps {
                dir('backend/user') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn clean verify sonar:sonar'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'backend/user/target/*.jar', fingerprint: true
            }
        }

        stage('Deploy (Manual Test Run Only)') {
            steps {
                dir('backend/user') {
                    bat 'java -jar target/user-0.0.1-SNAPSHOT.jar'
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}