  server:
    port: 8080
    address: 0.0.0.0

  spring:
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    mail:
      host: smtp.gmail.com
      port: 587
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update       # options: validate | update | create | create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

